export const TEMPLATES = [
    {
        id: 'navbar',
        title: 'Responsive Navbar',
        category: 'marketing',
        tags: ['nav', 'navigation', 'header', 'menu'],
        html: '<nav class="tmpl-navbar"><div class="tmpl-navbar-inner"><div class="tmpl-navbar-logo">Company</div><div class="tmpl-navbar-links"><a href="#">Home</a><a href="#">Features</a><a href="#">Pricing</a><a href="#">Contact</a></div><button class="tmpl-navbar-cta">Get Started</button></div></nav>',
        cssData: {
            '.tmpl-navbar': {
                background: '#ffffff',
                borderBottom: '1px solid #e2e8f0',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-navbar-inner': {
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                maxWidth: '1200px',
                margin: '0 auto',
                padding: '16px 24px',
            },
            '.tmpl-navbar-logo': {
                fontWeight: '700',
                fontSize: '1.25rem',
                color: '#1e293b',
            },
            '.tmpl-navbar-links': {
                display: 'flex',
                gap: '24px',
            },
            '.tmpl-navbar-links a': {
                color: '#64748b',
                textDecoration: 'none',
                fontSize: '0.9rem',
                fontWeight: '500',
            },
            '.tmpl-navbar-links a:hover': {
                color: '#2563eb',
            },
            '.tmpl-navbar-cta': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 20px',
                borderRadius: '6px',
                fontWeight: '600',
                fontSize: '0.85rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'hero-centered',
        title: 'Centered Hero',
        category: 'marketing',
        tags: ['landing', 'hero', 'cta', 'headline'],
        html: '<section class="tmpl-hero"><div class="tmpl-hero-content"><h1 class="tmpl-hero-title">Build Something Amazing</h1><p class="tmpl-hero-subtitle">Create stunning web layouts with our powerful visual builder. No code required — just drag, drop, and publish.</p><div class="tmpl-hero-actions"><button class="tmpl-hero-btn-primary">Get Started Free</button><button class="tmpl-hero-btn-secondary">Learn More</button></div></div></section>',
        cssData: {
            '.tmpl-hero': {
                minHeight: '80vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
                padding: '60px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-hero-content': {
                maxWidth: '720px',
                textAlign: 'center',
            },
            '.tmpl-hero-title': {
                fontSize: '3rem',
                fontWeight: '800',
                color: '#ffffff',
                margin: '0 0 16px',
                lineHeight: '1.2',
            },
            '.tmpl-hero-subtitle': {
                fontSize: '1.125rem',
                color: '#94a3b8',
                margin: '0 0 32px',
                lineHeight: '1.6',
            },
            '.tmpl-hero-actions': {
                display: 'flex',
                gap: '12px',
                justifyContent: 'center',
                flexWrap: 'wrap',
            },
            '.tmpl-hero-btn-primary': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '1rem',
                cursor: 'pointer',
            },
            '.tmpl-hero-btn-secondary': {
                background: 'transparent',
                color: '#e2e8f0',
                border: '1px solid #475569',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '1rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'pricing-table',
        title: 'Pricing Table',
        category: 'marketing',
        tags: ['pricing', 'plans', 'features', 'columns'],
        html: '<section class="tmpl-pricing"><h2 class="tmpl-pricing-title">Choose Your Plan</h2><div class="tmpl-pricing-grid"><div class="tmpl-pricing-card"><h3 class="tmpl-pricing-card-title">Starter</h3><p class="tmpl-pricing-card-price">$9<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>5 Projects</li><li>Basic Components</li><li>Email Support</li><li>1 User</li></ul><button class="tmpl-pricing-card-btn">Get Started</button></div><div class="tmpl-pricing-card tmpl-pricing-card-featured"><h3 class="tmpl-pricing-card-title">Pro</h3><p class="tmpl-pricing-card-price">$29<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>Unlimited Projects</li><li>All Components</li><li>Priority Support</li><li>Up to 10 Users</li></ul><button class="tmpl-pricing-card-btn tmpl-pricing-card-btn-featured">Get Started</button></div><div class="tmpl-pricing-card"><h3 class="tmpl-pricing-card-title">Enterprise</h3><p class="tmpl-pricing-card-price">$99<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>Everything in Pro</li><li>Custom Branding</li><li>Dedicated Support</li><li>Unlimited Users</li></ul><button class="tmpl-pricing-card-btn">Contact Us</button></div></div></section>',
        cssData: {
            '.tmpl-pricing': {
                padding: '80px 24px',
                background: '#f8fafc',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-pricing-title': {
                fontSize: '2rem',
                fontWeight: '700',
                textAlign: 'center',
                color: '#1e293b',
                margin: '0 0 48px',
            },
            '.tmpl-pricing-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
                gap: '24px',
                maxWidth: '960px',
                margin: '0 auto',
            },
            '.tmpl-pricing-card': {
                background: '#ffffff',
                border: '1px solid #e2e8f0',
                borderRadius: '12px',
                padding: '32px',
                display: 'flex',
                flexDirection: 'column',
            },
            '.tmpl-pricing-card-featured': {
                border: '2px solid #2563eb',
                background: '#eff6ff',
                transform: 'scale(1.05)',
            },
            '.tmpl-pricing-card-title': {
                fontSize: '1.25rem',
                fontWeight: '700',
                color: '#1e293b',
                margin: '0 0 8px',
            },
            '.tmpl-pricing-card-price': {
                fontSize: '2.5rem',
                fontWeight: '800',
                color: '#2563eb',
                margin: '0 0 24px',
            },
            '.tmpl-pricing-card-period': {
                fontSize: '1rem',
                fontWeight: '400',
                color: '#64748b',
            },
            '.tmpl-pricing-card-features': {
                listStyle: 'none',
                padding: '0',
                margin: '0 0 32px',
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
                flex: '1',
            },
            '.tmpl-pricing-card-features li': {
                fontSize: '0.9rem',
                color: '#475569',
                paddingLeft: '20px',
                position: 'relative',
            },
            '.tmpl-pricing-card-features li::before': {
                content: '"✓"',
                position: 'absolute',
                left: '0',
                color: '#2563eb',
                fontWeight: '700',
            },
            '.tmpl-pricing-card-btn': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.9rem',
                cursor: 'pointer',
                width: '100%',
            },
            '.tmpl-pricing-card-btn-featured': {
                background: '#1d4ed8',
            },
        },
    },
    {
        id: 'footer',
        title: 'Footer with Columns',
        category: 'marketing',
        tags: ['footer', 'links', 'columns', 'contact'],
        html: '<footer class="tmpl-footer"><div class="tmpl-footer-grid"><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Company</h4><p class="tmpl-footer-text">Building the future of web design, one component at a time.</p></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Product</h4><ul class="tmpl-footer-links"><li><a href="#">Features</a></li><li><a href="#">Pricing</a></li><li><a href="#">Integrations</a></li><li><a href="#">Changelog</a></li></ul></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Company</h4><ul class="tmpl-footer-links"><li><a href="#">About</a></li><li><a href="#">Blog</a></li><li><a href="#">Careers</a></li><li><a href="#">Press</a></li></ul></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Legal</h4><ul class="tmpl-footer-links"><li><a href="#">Privacy</a></li><li><a href="#">Terms</a></li><li><a href="#">Cookies</a></li><li><a href="#">Licenses</a></li></ul></div></div><div class="tmpl-footer-bottom"><p>&copy; 2026 LayoutCraft Studio. All rights reserved.</p></div></footer>',
        cssData: {
            '.tmpl-footer': {
                background: '#0f172a',
                color: '#e2e8f0',
                fontFamily: 'system-ui, sans-serif',
                padding: '60px 24px 0',
            },
            '.tmpl-footer-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                gap: '40px',
                maxWidth: '1200px',
                margin: '0 auto',
            },
            '.tmpl-footer-col': {},
            '.tmpl-footer-heading': {
                fontSize: '0.85rem',
                fontWeight: '600',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
                color: '#94a3b8',
                margin: '0 0 16px',
            },
            '.tmpl-footer-text': {
                fontSize: '0.85rem',
                color: '#64748b',
                lineHeight: '1.6',
                margin: '0',
            },
            '.tmpl-footer-links': {
                listStyle: 'none',
                padding: '0',
                margin: '0',
                display: 'flex',
                flexDirection: 'column',
                gap: '10px',
            },
            '.tmpl-footer-links a': {
                color: '#94a3b8',
                textDecoration: 'none',
                fontSize: '0.85rem',
            },
            '.tmpl-footer-links a:hover': {
                color: '#ffffff',
            },
            '.tmpl-footer-bottom': {
                borderTop: '1px solid #1e293b',
                marginTop: '48px',
                padding: '24px 0',
                textAlign: 'center',
            },
            '.tmpl-footer-bottom p': {
                fontSize: '0.8rem',
                color: '#475569',
                margin: '0',
            },
        },
    },
    {
        id: 'login-form',
        title: 'Login Form',
        category: 'forms',
        tags: ['login', 'form', 'auth', 'card'],
        html: '<section class="tmpl-login"><div class="tmpl-login-card"><div class="tmpl-login-header"><h2 class="tmpl-login-title">Welcome Back</h2><p class="tmpl-login-subtitle">Sign in to your account to continue.</p></div><form class="tmpl-login-form"><div class="tmpl-login-field"><label class="tmpl-login-label" for="login-email">Email</label><input class="tmpl-login-input" id="login-email" type="email" placeholder="you@example.com" /></div><div class="tmpl-login-field"><label class="tmpl-login-label" for="login-password">Password</label><input class="tmpl-login-input" id="login-password" type="password" placeholder="Enter your password" /></div><button class="tmpl-login-submit" type="submit">Sign In</button></form><div class="tmpl-login-footer"><p>Don\'t have an account? <a href="#">Sign up</a></p></div></div></section>',
        cssData: {
            '.tmpl-login': {
                minHeight: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: '#f1f5f9',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-login-card': {
                background: '#ffffff',
                borderRadius: '12px',
                padding: '40px',
                width: '100%',
                maxWidth: '420px',
                boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
            },
            '.tmpl-login-header': {
                textAlign: 'center',
                marginBottom: '32px',
            },
            '.tmpl-login-title': {
                fontSize: '1.5rem',
                fontWeight: '700',
                color: '#1e293b',
                margin: '0 0 8px',
            },
            '.tmpl-login-subtitle': {
                fontSize: '0.9rem',
                color: '#64748b',
                margin: '0',
            },
            '.tmpl-login-form': {
                display: 'flex',
                flexDirection: 'column',
                gap: '20px',
            },
            '.tmpl-login-field': {
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
            },
            '.tmpl-login-label': {
                fontSize: '0.85rem',
                fontWeight: '600',
                color: '#334155',
            },
            '.tmpl-login-input': {
                padding: '10px 14px',
                border: '1px solid #cbd5e1',
                borderRadius: '6px',
                fontSize: '0.9rem',
                outline: 'none',
                transition: 'border-color 0.15s',
            },
            '.tmpl-login-input:focus': {
                borderColor: '#2563eb',
                boxShadow: '0 0 0 3px rgba(37,99,235,0.1)',
            },
            '.tmpl-login-submit': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '6px',
                fontWeight: '600',
                fontSize: '0.9rem',
                cursor: 'pointer',
                marginTop: '8px',
            },
            '.tmpl-login-submit:hover': {
                background: '#1d4ed8',
            },
            '.tmpl-login-footer': {
                textAlign: 'center',
                marginTop: '24px',
            },
            '.tmpl-login-footer p': {
                fontSize: '0.85rem',
                color: '#64748b',
                margin: '0',
            },
            '.tmpl-login-footer a': {
                color: '#2563eb',
                textDecoration: 'none',
                fontWeight: '600',
            },
        },
    },
];
