export const TEMPLATES = [
    {
        id: 'navbar',
        title: 'Responsive Navbar',
        category: 'marketing',
        tags: ['nav', 'navigation', 'header', 'menu'],
        html: '<nav class="tmpl-navbar"><div class="tmpl-navbar-inner"><div class="tmpl-navbar-logo">Company</div><div class="tmpl-navbar-links"><a href="#">Home</a><a href="#">Features</a><a href="#">Pricing</a><a href="#">Contact</a></div><button class="tmpl-navbar-cta">Get Started</button></div></nav>',
        cssData: {
            '.tmpl-navbar': {
                background: '#ffffff',
                borderBottom: '1px solid #e2e8f0',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-navbar-inner': {
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                maxWidth: '1200px',
                margin: '0 auto',
                padding: '16px 24px',
            },
            '.tmpl-navbar-logo': {
                fontWeight: '700',
                fontSize: '1.25rem',
                color: '#1e293b',
            },
            '.tmpl-navbar-links': {
                display: 'flex',
                gap: '24px',
            },
            '.tmpl-navbar-links a': {
                color: '#64748b',
                textDecoration: 'none',
                fontSize: '0.9rem',
                fontWeight: '500',
            },
            '.tmpl-navbar-links a:hover': {
                color: '#2563eb',
            },
            '.tmpl-navbar-cta': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 20px',
                borderRadius: '6px',
                fontWeight: '600',
                fontSize: '0.85rem',
                cursor: 'pointer',
            },
        },
        tokens: {
            '--color-primary': '#2563eb',
            '--color-text': '#1e293b',
            '--color-text-muted': '#64748b',
            '--color-bg': '#ffffff',
            '--radius': '6px',
            '--space': '24px',
            '--font-base': 'system-ui, sans-serif',
        },
    },
    {
        id: 'hero-centered',
        title: 'Centered Hero',
        category: 'marketing',
        tags: ['landing', 'hero', 'cta', 'headline'],
        html: '<section class="tmpl-hero"><div class="tmpl-hero-content"><h1 class="tmpl-hero-title">Build Something Amazing</h1><p class="tmpl-hero-subtitle">Create stunning web layouts with our powerful visual builder. No code required — just drag, drop, and publish.</p><div class="tmpl-hero-actions"><button class="tmpl-hero-btn-primary">Get Started Free</button><button class="tmpl-hero-btn-secondary">Learn More</button></div></div></section>',
        cssData: {
            '.tmpl-hero': {
                minHeight: '80vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
                padding: '60px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-hero-content': {
                maxWidth: '720px',
                textAlign: 'center',
            },
            '.tmpl-hero-title': {
                fontSize: '3rem',
                fontWeight: '800',
                color: '#ffffff',
                margin: '0 0 16px',
                lineHeight: '1.2',
            },
            '.tmpl-hero-subtitle': {
                fontSize: '1.125rem',
                color: '#94a3b8',
                margin: '0 0 32px',
                lineHeight: '1.6',
            },
            '.tmpl-hero-actions': {
                display: 'flex',
                gap: '12px',
                justifyContent: 'center',
                flexWrap: 'wrap',
            },
            '.tmpl-hero-btn-primary': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '1rem',
                cursor: 'pointer',
            },
            '.tmpl-hero-btn-secondary': {
                background: 'transparent',
                color: '#e2e8f0',
                border: '1px solid #475569',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '1rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'pricing-table',
        title: 'Pricing Table',
        category: 'marketing',
        tags: ['pricing', 'plans', 'features', 'columns'],
        html: '<section class="tmpl-pricing"><h2 class="tmpl-pricing-title">Choose Your Plan</h2><div class="tmpl-pricing-grid"><div class="tmpl-pricing-card"><h3 class="tmpl-pricing-card-title">Starter</h3><p class="tmpl-pricing-card-price">$9<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>5 Projects</li><li>Basic Components</li><li>Email Support</li><li>1 User</li></ul><button class="tmpl-pricing-card-btn">Get Started</button></div><div class="tmpl-pricing-card tmpl-pricing-card-featured"><h3 class="tmpl-pricing-card-title">Pro</h3><p class="tmpl-pricing-card-price">$29<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>Unlimited Projects</li><li>All Components</li><li>Priority Support</li><li>Up to 10 Users</li></ul><button class="tmpl-pricing-card-btn tmpl-pricing-card-btn-featured">Get Started</button></div><div class="tmpl-pricing-card"><h3 class="tmpl-pricing-card-title">Enterprise</h3><p class="tmpl-pricing-card-price">$99<span class="tmpl-pricing-card-period">/mo</span></p><ul class="tmpl-pricing-card-features"><li>Everything in Pro</li><li>Custom Branding</li><li>Dedicated Support</li><li>Unlimited Users</li></ul><button class="tmpl-pricing-card-btn">Contact Us</button></div></div></section>',
        cssData: {
            '.tmpl-pricing': {
                padding: '80px 24px',
                background: '#f8fafc',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-pricing-title': {
                fontSize: '2rem',
                fontWeight: '700',
                textAlign: 'center',
                color: '#1e293b',
                margin: '0 0 48px',
            },
            '.tmpl-pricing-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
                gap: '24px',
                maxWidth: '960px',
                margin: '0 auto',
            },
            '.tmpl-pricing-card': {
                background: '#ffffff',
                border: '1px solid #e2e8f0',
                borderRadius: '12px',
                padding: '32px',
                display: 'flex',
                flexDirection: 'column',
            },
            '.tmpl-pricing-card-featured': {
                border: '2px solid #2563eb',
                background: '#eff6ff',
                transform: 'scale(1.05)',
            },
            '.tmpl-pricing-card-title': {
                fontSize: '1.25rem',
                fontWeight: '700',
                color: '#1e293b',
                margin: '0 0 8px',
            },
            '.tmpl-pricing-card-price': {
                fontSize: '2.5rem',
                fontWeight: '800',
                color: '#2563eb',
                margin: '0 0 24px',
            },
            '.tmpl-pricing-card-period': {
                fontSize: '1rem',
                fontWeight: '400',
                color: '#64748b',
            },
            '.tmpl-pricing-card-features': {
                listStyle: 'none',
                padding: '0',
                margin: '0 0 32px',
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
                flex: '1',
            },
            '.tmpl-pricing-card-features li': {
                fontSize: '0.9rem',
                color: '#475569',
                paddingLeft: '20px',
                position: 'relative',
            },
            '.tmpl-pricing-card-features li::before': {
                content: '"✓"',
                position: 'absolute',
                left: '0',
                color: '#2563eb',
                fontWeight: '700',
            },
            '.tmpl-pricing-card-btn': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.9rem',
                cursor: 'pointer',
                width: '100%',
            },
            '.tmpl-pricing-card-btn-featured': {
                background: '#1d4ed8',
            },
        },
    },
    {
        id: 'footer',
        title: 'Footer with Columns',
        category: 'marketing',
        tags: ['footer', 'links', 'columns', 'contact'],
        html: '<footer class="tmpl-footer"><div class="tmpl-footer-grid"><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Company</h4><p class="tmpl-footer-text">Building the future of web design, one component at a time.</p></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Product</h4><ul class="tmpl-footer-links"><li><a href="#">Features</a></li><li><a href="#">Pricing</a></li><li><a href="#">Integrations</a></li><li><a href="#">Changelog</a></li></ul></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Company</h4><ul class="tmpl-footer-links"><li><a href="#">About</a></li><li><a href="#">Blog</a></li><li><a href="#">Careers</a></li><li><a href="#">Press</a></li></ul></div><div class="tmpl-footer-col"><h4 class="tmpl-footer-heading">Legal</h4><ul class="tmpl-footer-links"><li><a href="#">Privacy</a></li><li><a href="#">Terms</a></li><li><a href="#">Cookies</a></li><li><a href="#">Licenses</a></li></ul></div></div><div class="tmpl-footer-bottom"><p>&copy; 2026 LayoutCraft Studio. All rights reserved.</p></div></footer>',
        cssData: {
            '.tmpl-footer': {
                background: '#0f172a',
                color: '#e2e8f0',
                fontFamily: 'system-ui, sans-serif',
                padding: '60px 24px 0',
            },
            '.tmpl-footer-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                gap: '40px',
                maxWidth: '1200px',
                margin: '0 auto',
            },
            '.tmpl-footer-col': {},
            '.tmpl-footer-heading': {
                fontSize: '0.85rem',
                fontWeight: '600',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
                color: '#94a3b8',
                margin: '0 0 16px',
            },
            '.tmpl-footer-text': {
                fontSize: '0.85rem',
                color: '#64748b',
                lineHeight: '1.6',
                margin: '0',
            },
            '.tmpl-footer-links': {
                listStyle: 'none',
                padding: '0',
                margin: '0',
                display: 'flex',
                flexDirection: 'column',
                gap: '10px',
            },
            '.tmpl-footer-links a': {
                color: '#94a3b8',
                textDecoration: 'none',
                fontSize: '0.85rem',
            },
            '.tmpl-footer-links a:hover': {
                color: '#ffffff',
            },
            '.tmpl-footer-bottom': {
                borderTop: '1px solid #1e293b',
                marginTop: '48px',
                padding: '24px 0',
                textAlign: 'center',
            },
            '.tmpl-footer-bottom p': {
                fontSize: '0.8rem',
                color: '#475569',
                margin: '0',
            },
        },
    },
    {
        id: 'login-form',
        title: 'Login Form',
        category: 'forms',
        tags: ['login', 'form', 'auth', 'card'],
        html: '<section class="tmpl-login"><div class="tmpl-login-card"><div class="tmpl-login-header"><h2 class="tmpl-login-title">Welcome Back</h2><p class="tmpl-login-subtitle">Sign in to your account to continue.</p></div><form class="tmpl-login-form"><div class="tmpl-login-field"><label class="tmpl-login-label" for="login-email">Email</label><input class="tmpl-login-input" id="login-email" type="email" placeholder="you@example.com" /></div><div class="tmpl-login-field"><label class="tmpl-login-label" for="login-password">Password</label><input class="tmpl-login-input" id="login-password" type="password" placeholder="Enter your password" /></div><button class="tmpl-login-submit" type="submit">Sign In</button></form><div class="tmpl-login-footer"><p>Don\'t have an account? <a href="#">Sign up</a></p></div></div></section>',
        cssData: {
            '.tmpl-login': {
                minHeight: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: '#f1f5f9',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-login-card': {
                background: '#ffffff',
                borderRadius: '12px',
                padding: '40px',
                width: '100%',
                maxWidth: '420px',
                boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
            },
            '.tmpl-login-header': {
                textAlign: 'center',
                marginBottom: '32px',
            },
            '.tmpl-login-title': {
                fontSize: '1.5rem',
                fontWeight: '700',
                color: '#1e293b',
                margin: '0 0 8px',
            },
            '.tmpl-login-subtitle': {
                fontSize: '0.9rem',
                color: '#64748b',
                margin: '0',
            },
            '.tmpl-login-form': {
                display: 'flex',
                flexDirection: 'column',
                gap: '20px',
            },
            '.tmpl-login-field': {
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
            },
            '.tmpl-login-label': {
                fontSize: '0.85rem',
                fontWeight: '600',
                color: '#334155',
            },
            '.tmpl-login-input': {
                padding: '10px 14px',
                border: '1px solid #cbd5e1',
                borderRadius: '6px',
                fontSize: '0.9rem',
                outline: 'none',
                transition: 'border-color 0.15s',
            },
            '.tmpl-login-input:focus': {
                borderColor: '#2563eb',
                boxShadow: '0 0 0 3px rgba(37,99,235,0.1)',
            },
            '.tmpl-login-submit': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '6px',
                fontWeight: '600',
                fontSize: '0.9rem',
                cursor: 'pointer',
                marginTop: '8px',
            },
            '.tmpl-login-submit:hover': {
                background: '#1d4ed8',
            },
            '.tmpl-login-footer': {
                textAlign: 'center',
                marginTop: '24px',
            },
            '.tmpl-login-footer p': {
                fontSize: '0.85rem',
                color: '#64748b',
                margin: '0',
            },
            '.tmpl-login-footer a': {
                color: '#2563eb',
                textDecoration: 'none',
                fontWeight: '600',
            },
        },
    },
    {
        id: 'hero-split',
        title: 'Split Hero with Image',
        category: 'marketing',
        tags: ['hero', 'landing', 'split', 'image', 'cta'],
        html: '<section class="tmpl-split"><div class="tmpl-split-text"><span class="tmpl-split-badge">New: LayoutCraft 2.0</span><h1 class="tmpl-split-title">Design beautiful pages in minutes</h1><p class="tmpl-split-desc">A visual builder for teams that want pixel-perfect results without fighting code. Drag, style, export — done.</p><div class="tmpl-split-actions"><button class="tmpl-split-btn-primary">Start Free Trial</button><a class="tmpl-split-btn-link" href="#">Watch demo →</a></div></div><div class="tmpl-split-media"><div class="tmpl-split-card"><div class="tmpl-split-card-bar"><span></span><span></span><span></span></div><div class="tmpl-split-card-line"></div><div class="tmpl-split-card-line"></div><div class="tmpl-split-card-line short"></div><div class="tmpl-split-card-pill"></div></div></div></section>',
        cssData: {
            '.tmpl-split': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
                gap: '48px',
                alignItems: 'center',
                maxWidth: '1200px',
                margin: '0 auto',
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-split-badge': {
                display: 'inline-block',
                background: '#eff6ff',
                color: '#2563eb',
                fontSize: '0.75rem',
                fontWeight: '700',
                padding: '6px 12px',
                borderRadius: '999px',
                marginBottom: '16px',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
            },
            '.tmpl-split-title': {
                fontSize: '2.75rem',
                fontWeight: '800',
                lineHeight: '1.15',
                color: '#0f172a',
                margin: '0 0 16px',
            },
            '.tmpl-split-desc': {
                fontSize: '1.125rem',
                lineHeight: '1.7',
                color: '#64748b',
                margin: '0 0 32px',
                maxWidth: '480px',
            },
            '.tmpl-split-actions': {
                display: 'flex',
                alignItems: 'center',
                gap: '20px',
                flexWrap: 'wrap',
            },
            '.tmpl-split-btn-primary': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.95rem',
                cursor: 'pointer',
            },
            '.tmpl-split-btn-link': {
                color: '#2563eb',
                textDecoration: 'none',
                fontWeight: '600',
                fontSize: '0.95rem',
            },
            '.tmpl-split-media': {
                display: 'flex',
                justifyContent: 'center',
            },
            '.tmpl-split-card': {
                width: '100%',
                maxWidth: '420px',
                background: 'linear-gradient(135deg, #1e293b, #0f172a)',
                borderRadius: '16px',
                padding: '24px',
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
                boxShadow: '0 24px 48px rgba(15,23,42,0.25)',
            },
            '.tmpl-split-card-bar': {
                display: 'flex',
                gap: '6px',
                marginBottom: '12px',
            },
            '.tmpl-split-card-bar span': {
                width: '10px',
                height: '10px',
                borderRadius: '50%',
                background: '#475569',
            },
            '.tmpl-split-card-line': {
                height: '14px',
                borderRadius: '4px',
                background: '#334155',
            },
            '.tmpl-split-card-line.short': {
                width: '60%',
            },
            '.tmpl-split-card-pill': {
                height: '40px',
                borderRadius: '8px',
                background: 'linear-gradient(90deg, #2563eb, #3b82f6)',
                marginTop: '12px',
            },
        },
    },
    {
        id: 'feature-grid',
        title: 'Feature Grid',
        category: 'marketing',
        tags: ['features', 'grid', 'benefits', 'cards'],
        html: '<section class="tmpl-features"><h2 class="tmpl-features-title">Everything you need</h2><p class="tmpl-features-subtitle">Powerful building blocks that work together seamlessly.</p><div class="tmpl-features-grid"><div class="tmpl-feature-card"><div class="tmpl-feature-icon">⚡</div><h3 class="tmpl-feature-name">Lightning Fast</h3><p class="tmpl-feature-desc">Snappy interactions and instant previews keep your flow uninterrupted.</p></div><div class="tmpl-feature-card"><div class="tmpl-feature-icon">🎨</div><h3 class="tmpl-feature-name">Beautiful by Default</h3><p class="tmpl-feature-desc">Every component ships with tasteful defaults you can fine-tune.</p></div><div class="tmpl-feature-card"><div class="tmpl-feature-icon">🔌</div><h3 class="tmpl-feature-name">100+ Integrations</h3><p class="tmpl-feature-desc">Connect your stack with one-click integrations and webhooks.</p></div><div class="tmpl-feature-card"><div class="tmpl-feature-icon">🛡️</div><h3 class="tmpl-feature-name">Enterprise Security</h3><p class="tmpl-feature-desc">SSO, audit logs and granular permissions built in from day one.</p></div></div></section>',
        cssData: {
            '.tmpl-features': {
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
                maxWidth: '1200px',
                margin: '0 auto',
            },
            '.tmpl-features-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 12px',
            },
            '.tmpl-features-subtitle': {
                fontSize: '1.05rem',
                textAlign: 'center',
                color: '#64748b',
                margin: '0 0 48px',
            },
            '.tmpl-features-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
                gap: '24px',
            },
            '.tmpl-feature-card': {
                background: '#ffffff',
                border: '1px solid #e2e8f0',
                borderRadius: '12px',
                padding: '28px',
                transition: 'box-shadow 0.2s, transform 0.2s',
            },
            '.tmpl-feature-card:hover': {
                boxShadow: '0 12px 32px rgba(15,23,42,0.1)',
                transform: 'translateY(-4px)',
            },
            '.tmpl-feature-icon': {
                fontSize: '1.75rem',
                marginBottom: '16px',
            },
            '.tmpl-feature-name': {
                fontSize: '1.1rem',
                fontWeight: '700',
                color: '#0f172a',
                margin: '0 0 8px',
            },
            '.tmpl-feature-desc': {
                fontSize: '0.9rem',
                lineHeight: '1.6',
                color: '#64748b',
                margin: '0',
            },
        },
    },
    {
        id: 'testimonials',
        title: 'Testimonials',
        category: 'marketing',
        tags: ['testimonials', 'quotes', 'social-proof', 'review'],
        html: '<section class="tmpl-testimonials"><h2 class="tmpl-testimonials-title">Loved by teams worldwide</h2><div class="tmpl-testimonials-grid"><div class="tmpl-testimonial-card"><p class="tmpl-testimonial-quote">"LayoutCraft replaced our entire front-end sprint. We ship mockups to production in hours, not weeks."</p><div class="tmpl-testimonial-author"><div class="tmpl-testimonial-avatar">SM</div><div class="tmpl-testimonial-meta"><span class="tmpl-testimonial-name">Sara Miller</span><span class="tmpl-testimonial-role">Product Lead, Acme</span></div></div></div><div class="tmpl-testimonial-card"><p class="tmpl-testimonial-quote">"The visual CSS builder is a game changer for our design-to-dev handoff. Zero context switching."</p><div class="tmpl-testimonial-author"><div class="tmpl-testimonial-avatar">JK</div><div class="tmpl-testimonial-meta"><span class="tmpl-testimonial-name">James Kim</span><span class="tmpl-testimonial-role">CTO, Northwind</span></div></div></div><div class="tmpl-testimonial-card"><p class="tmpl-testimonial-quote">"We adopted it company-wide after one demo. Non-developers build real pages now."</p><div class="tmpl-testimonial-author"><div class="tmpl-testimonial-avatar">AT</div><div class="tmpl-testimonial-meta"><span class="tmpl-testimonial-name">Ana Torres</span><span class="tmpl-testimonial-role">Head of Design, Globex</span></div></div></div></div></section>',
        cssData: {
            '.tmpl-testimonials': {
                background: '#f8fafc',
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-testimonials-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 48px',
            },
            '.tmpl-testimonials-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
                gap: '24px',
                maxWidth: '1100px',
                margin: '0 auto',
            },
            '.tmpl-testimonial-card': {
                background: '#ffffff',
                borderRadius: '12px',
                padding: '28px',
                boxShadow: '0 4px 16px rgba(15,23,42,0.06)',
                display: 'flex',
                flexDirection: 'column',
                gap: '20px',
            },
            '.tmpl-testimonial-quote': {
                fontSize: '0.95rem',
                lineHeight: '1.7',
                color: '#334155',
                margin: '0',
                flex: '1',
            },
            '.tmpl-testimonial-author': {
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
            },
            '.tmpl-testimonial-avatar': {
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: '#2563eb',
                color: '#ffffff',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '0.8rem',
                fontWeight: '700',
                flexShrink: '0',
            },
            '.tmpl-testimonial-meta': {
                display: 'flex',
                flexDirection: 'column',
            },
            '.tmpl-testimonial-name': {
                fontSize: '0.9rem',
                fontWeight: '700',
                color: '#0f172a',
            },
            '.tmpl-testimonial-role': {
                fontSize: '0.8rem',
                color: '#94a3b8',
            },
        },
    },
    {
        id: 'cta-banner',
        title: 'CTA Banner',
        category: 'marketing',
        tags: ['cta', 'call-to-action', 'banner', 'signup'],
        html: '<section class="tmpl-cta"><div class="tmpl-cta-inner"><h2 class="tmpl-cta-title">Ready to build something great?</h2><p class="tmpl-cta-subtitle">Join 12,000+ creators who ship pages with LayoutCraft every day.</p><div class="tmpl-cta-actions"><button class="tmpl-cta-btn-primary">Create Free Account</button><button class="tmpl-cta-btn-ghost">Talk to Sales</button></div></div></section>',
        cssData: {
            '.tmpl-cta': {
                background: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-cta-inner': {
                maxWidth: '720px',
                margin: '0 auto',
                textAlign: 'center',
            },
            '.tmpl-cta-title': {
                fontSize: '2.5rem',
                fontWeight: '800',
                color: '#ffffff',
                margin: '0 0 16px',
            },
            '.tmpl-cta-subtitle': {
                fontSize: '1.1rem',
                color: '#bfdbfe',
                margin: '0 0 32px',
            },
            '.tmpl-cta-actions': {
                display: 'flex',
                gap: '12px',
                justifyContent: 'center',
                flexWrap: 'wrap',
            },
            '.tmpl-cta-btn-primary': {
                background: '#ffffff',
                color: '#1e3a8a',
                border: 'none',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '700',
                fontSize: '0.95rem',
                cursor: 'pointer',
            },
            '.tmpl-cta-btn-ghost': {
                background: 'transparent',
                color: '#ffffff',
                border: '1px solid rgba(255,255,255,0.4)',
                padding: '14px 28px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.95rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'stats-section',
        title: 'Stats Section',
        category: 'marketing',
        tags: ['stats', 'metrics', 'numbers', 'proof'],
        html: '<section class="tmpl-stats"><div class="tmpl-stats-item"><span class="tmpl-stats-value">12k+</span><span class="tmpl-stats-label">Active users</span></div><div class="tmpl-stats-item"><span class="tmpl-stats-value">99.9%</span><span class="tmpl-stats-label">Uptime</span></div><div class="tmpl-stats-item"><span class="tmpl-stats-value">4.8/5</span><span class="tmpl-stats-label">Average rating</span></div><div class="tmpl-stats-item"><span class="tmpl-stats-value">180+</span><span class="tmpl-stats-label">Countries served</span></div></section>',
        cssData: {
            '.tmpl-stats': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                gap: '24px',
                padding: '64px 24px',
                maxWidth: '1100px',
                margin: '0 auto',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-stats-item': {
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: '8px',
                padding: '24px',
                borderLeft: '2px solid #e2e8f0',
            },
            '.tmpl-stats-value': {
                fontSize: '2.5rem',
                fontWeight: '800',
                color: '#2563eb',
                lineHeight: '1',
            },
            '.tmpl-stats-label': {
                fontSize: '0.85rem',
                color: '#64748b',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
            },
        },
    },
    {
        id: 'team-section',
        title: 'Team Section',
        category: 'marketing',
        tags: ['team', 'people', 'about', 'avatars'],
        html: '<section class="tmpl-team"><h2 class="tmpl-team-title">Meet the team</h2><div class="tmpl-team-grid"><div class="tmpl-team-member"><div class="tmpl-team-avatar">AL</div><h3 class="tmpl-team-name">Alex Liu</h3><span class="tmpl-team-role">Co-founder &amp; CEO</span></div><div class="tmpl-team-member"><div class="tmpl-team-avatar">RB</div><h3 class="tmpl-team-name">Rosa Bianchi</h3><span class="tmpl-team-role">Head of Design</span></div><div class="tmpl-team-member"><div class="tmpl-team-avatar">MO</div><h3 class="tmpl-team-name">Marcus Okafor</h3><span class="tmpl-team-role">Lead Engineer</span></div><div class="tmpl-team-member"><div class="tmpl-team-avatar">YJ</div><h3 class="tmpl-team-name">Yuki Jensen</h3><span class="tmpl-team-role">Developer Relations</span></div></div></section>',
        cssData: {
            '.tmpl-team': {
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
                maxWidth: '1100px',
                margin: '0 auto',
            },
            '.tmpl-team-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 48px',
            },
            '.tmpl-team-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                gap: '32px',
            },
            '.tmpl-team-member': {
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                textAlign: 'center',
                gap: '8px',
            },
            '.tmpl-team-avatar': {
                width: '80px',
                height: '80px',
                borderRadius: '50%',
                background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
                color: '#ffffff',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.5rem',
                fontWeight: '700',
                marginBottom: '8px',
            },
            '.tmpl-team-name': {
                fontSize: '1.05rem',
                fontWeight: '700',
                color: '#0f172a',
                margin: '0',
            },
            '.tmpl-team-role': {
                fontSize: '0.85rem',
                color: '#94a3b8',
            },
        },
    },
    {
        id: 'blog-card',
        title: 'Blog Card List',
        category: 'marketing',
        tags: ['blog', 'articles', 'cards', 'news'],
        html: '<section class="tmpl-blog"><h2 class="tmpl-blog-title">Latest articles</h2><div class="tmpl-blog-grid"><article class="tmpl-blog-card"><div class="tmpl-blog-thumb"></div><div class="tmpl-blog-body"><span class="tmpl-blog-tag">Design</span><h3 class="tmpl-blog-heading">10 layout patterns that convert</h3><p class="tmpl-blog-excerpt">Proven page structures for landing pages that keep visitors scrolling.</p><span class="tmpl-blog-meta">May 12 · 6 min read</span></div></article><article class="tmpl-blog-card"><div class="tmpl-blog-thumb"></div><div class="tmpl-blog-body"><span class="tmpl-blog-tag">Engineering</span><h3 class="tmpl-blog-heading">How we built the CSS engine</h3><p class="tmpl-blog-excerpt">A look under the hood at rule trees, specificity and live compilation.</p><span class="tmpl-blog-meta">Apr 28 · 9 min read</span></div></article><article class="tmpl-blog-card"><div class="tmpl-blog-thumb"></div><div class="tmpl-blog-body"><span class="tmpl-blog-tag">Product</span><h3 class="tmpl-blog-heading">Shipping faster with templates</h3><p class="tmpl-blog-excerpt">How teams cut mockup-to-production time using drop-in template kits.</p><span class="tmpl-blog-meta">Apr 03 · 5 min read</span></div></article></div></section>',
        cssData: {
            '.tmpl-blog': {
                padding: '80px 24px',
                background: '#f8fafc',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-blog-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 48px',
            },
            '.tmpl-blog-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
                gap: '24px',
                maxWidth: '1100px',
                margin: '0 auto',
            },
            '.tmpl-blog-card': {
                background: '#ffffff',
                borderRadius: '12px',
                overflow: 'hidden',
                boxShadow: '0 4px 16px rgba(15,23,42,0.06)',
                display: 'flex',
                flexDirection: 'column',
            },
            '.tmpl-blog-thumb': {
                height: '140px',
                background: 'linear-gradient(135deg, #dbeafe, #c7d2fe)',
            },
            '.tmpl-blog-body': {
                padding: '20px',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px',
                flex: '1',
            },
            '.tmpl-blog-tag': {
                alignSelf: 'flex-start',
                fontSize: '0.7rem',
                fontWeight: '700',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
                color: '#2563eb',
                background: '#eff6ff',
                padding: '4px 10px',
                borderRadius: '999px',
            },
            '.tmpl-blog-heading': {
                fontSize: '1.1rem',
                fontWeight: '700',
                color: '#0f172a',
                margin: '0',
                lineHeight: '1.4',
            },
            '.tmpl-blog-excerpt': {
                fontSize: '0.85rem',
                lineHeight: '1.6',
                color: '#64748b',
                margin: '0',
                flex: '1',
            },
            '.tmpl-blog-meta': {
                fontSize: '0.75rem',
                color: '#94a3b8',
            },
        },
    },
    {
        id: 'faq-list',
        title: 'FAQ List',
        category: 'marketing',
        tags: ['faq', 'questions', 'support', 'accordion'],
        html: '<section class="tmpl-faq"><h2 class="tmpl-faq-title">Frequently asked questions</h2><div class="tmpl-faq-list"><details class="tmpl-faq-item"><summary class="tmpl-faq-q">Is there a free plan?</summary><p class="tmpl-faq-a">Yes — the Starter plan is free forever with 5 projects and core components.</p></details><details class="tmpl-faq-item"><summary class="tmpl-faq-q">Can I export the code?</summary><p class="tmpl-faq-a">Absolutely. Export clean HTML/CSS, React JSX, Vue SFC or a Web Component.</p></details><details class="tmpl-faq-item"><summary class="tmpl-faq-q">Do I need to know CSS?</summary><p class="tmpl-faq-a">No. Use the visual editors; the tool generates the CSS for you.</p></details><details class="tmpl-faq-item"><summary class="tmpl-faq-q">Can I self-host?</summary><p class="tmpl-faq-a">Yes, LayoutCraft is open source and ships with a one-command Docker setup.</p></details></div></section>',
        cssData: {
            '.tmpl-faq': {
                padding: '80px 24px',
                maxWidth: '760px',
                margin: '0 auto',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-faq-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 48px',
            },
            '.tmpl-faq-list': {
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
            },
            '.tmpl-faq-item': {
                background: '#ffffff',
                border: '1px solid #e2e8f0',
                borderRadius: '10px',
                padding: '4px 20px',
            },
            '.tmpl-faq-q': {
                fontSize: '0.95rem',
                fontWeight: '600',
                color: '#0f172a',
                padding: '16px 0',
                cursor: 'pointer',
            },
            '.tmpl-faq-a': {
                fontSize: '0.9rem',
                lineHeight: '1.7',
                color: '#64748b',
                padding: '0 0 16px',
                margin: '0',
            },
        },
    },
    {
        id: 'dashboard-layout',
        title: 'Dashboard Shell',
        category: 'appshell',
        tags: ['dashboard', 'sidebar', 'layout', 'admin', 'analytics'],
        html: '<section class="tmpl-dashboard"><aside class="tmpl-dashboard-side"><div class="tmpl-dashboard-brand">Acme OS</div><nav class="tmpl-dashboard-nav"><a class="tmpl-dashboard-link active" href="#">Overview</a><a class="tmpl-dashboard-link" href="#">Analytics</a><a class="tmpl-dashboard-link" href="#">Projects</a><a class="tmpl-dashboard-link" href="#">Team</a><a class="tmpl-dashboard-link" href="#">Settings</a></nav></aside><main class="tmpl-dashboard-main"><header class="tmpl-dashboard-topbar"><h2 class="tmpl-dashboard-heading">Overview</h2><button class="tmpl-dashboard-btn">+ New Report</button></header><div class="tmpl-dashboard-cards"><div class="tmpl-dashboard-card"><span class="tmpl-dashboard-card-label">Revenue</span><span class="tmpl-dashboard-card-value">$48,290</span><span class="tmpl-dashboard-card-delta up">▲ 12.4%</span></div><div class="tmpl-dashboard-card"><span class="tmpl-dashboard-card-label">Active users</span><span class="tmpl-dashboard-card-value">3,842</span><span class="tmpl-dashboard-card-delta up">▲ 8.1%</span></div><div class="tmpl-dashboard-card"><span class="tmpl-dashboard-card-label">Churn rate</span><span class="tmpl-dashboard-card-value">1.9%</span><span class="tmpl-dashboard-card-delta down">▼ 0.4%</span></div></div></main></section>',
        cssData: {
            '.tmpl-dashboard': {
                display: 'grid',
                gridTemplateColumns: '240px 1fr',
                minHeight: '100vh',
                fontFamily: 'system-ui, sans-serif',
                background: '#f1f5f9',
            },
            '.tmpl-dashboard-side': {
                background: '#0f172a',
                padding: '24px 16px',
                display: 'flex',
                flexDirection: 'column',
                gap: '32px',
            },
            '.tmpl-dashboard-brand': {
                color: '#ffffff',
                fontSize: '1.1rem',
                fontWeight: '800',
                padding: '0 8px',
            },
            '.tmpl-dashboard-nav': {
                display: 'flex',
                flexDirection: 'column',
                gap: '4px',
            },
            '.tmpl-dashboard-link': {
                color: '#94a3b8',
                textDecoration: 'none',
                fontSize: '0.9rem',
                padding: '10px 12px',
                borderRadius: '8px',
            },
            '.tmpl-dashboard-link:hover': {
                color: '#e2e8f0',
                background: '#1e293b',
            },
            '.tmpl-dashboard-link.active': {
                color: '#ffffff',
                background: '#2563eb',
                fontWeight: '600',
            },
            '.tmpl-dashboard-main': {
                padding: '32px',
            },
            '.tmpl-dashboard-topbar': {
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '24px',
            },
            '.tmpl-dashboard-heading': {
                fontSize: '1.5rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0',
            },
            '.tmpl-dashboard-btn': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 18px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.85rem',
                cursor: 'pointer',
            },
            '.tmpl-dashboard-cards': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                gap: '16px',
            },
            '.tmpl-dashboard-card': {
                background: '#ffffff',
                borderRadius: '12px',
                padding: '20px',
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
                boxShadow: '0 2px 8px rgba(15,23,42,0.05)',
            },
            '.tmpl-dashboard-card-label': {
                fontSize: '0.8rem',
                color: '#64748b',
            },
            '.tmpl-dashboard-card-value': {
                fontSize: '1.75rem',
                fontWeight: '800',
                color: '#0f172a',
            },
            '.tmpl-dashboard-card-delta': {
                fontSize: '0.8rem',
                fontWeight: '600',
            },
            '.tmpl-dashboard-card-delta.up': {
                color: '#16a34a',
            },
            '.tmpl-dashboard-card-delta.down': {
                color: '#dc2626',
            },
        },
        tokens: {
            '--color-primary': '#2563eb',
            '--color-sidebar': '#0f172a',
            '--color-bg': '#f1f5f9',
            '--color-card': '#ffffff',
            '--color-text': '#0f172a',
            '--color-text-muted': '#64748b',
            '--radius': '8px',
            '--space': '16px',
            '--font-base': 'system-ui, sans-serif',
        },
    },
    {
        id: 'profile-card',
        title: 'Profile Card',
        category: 'appshell',
        tags: ['profile', 'avatar', 'user', 'card'],
        html: '<section class="tmpl-profile"><div class="tmpl-profile-card"><div class="tmpl-profile-banner"></div><div class="tmpl-profile-avatar">JC</div><h3 class="tmpl-profile-name">Jordan Chen</h3><span class="tmpl-profile-role">Senior Product Designer</span><p class="tmpl-profile-bio">Design systems enthusiast, coffee-powered, based in Taipei.</p><div class="tmpl-profile-stats"><div class="tmpl-profile-stat"><span class="tmpl-profile-stat-value">1.2k</span><span class="tmpl-profile-stat-label">Followers</span></div><div class="tmpl-profile-stat"><span class="tmpl-profile-stat-value">84</span><span class="tmpl-profile-stat-label">Projects</span></div><div class="tmpl-profile-stat"><span class="tmpl-profile-stat-value">36</span><span class="tmpl-profile-stat-label">Awards</span></div></div><button class="tmpl-profile-btn">Follow</button></div></section>',
        cssData: {
            '.tmpl-profile': {
                display: 'flex',
                justifyContent: 'center',
                padding: '48px 24px',
                background: '#f1f5f9',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-profile-card': {
                background: '#ffffff',
                borderRadius: '16px',
                width: '100%',
                maxWidth: '340px',
                overflow: 'hidden',
                boxShadow: '0 8px 24px rgba(15,23,42,0.1)',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                paddingBottom: '24px',
            },
            '.tmpl-profile-banner': {
                width: '100%',
                height: '96px',
                background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
            },
            '.tmpl-profile-avatar': {
                width: '84px',
                height: '84px',
                borderRadius: '50%',
                background: '#ffffff',
                color: '#2563eb',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.5rem',
                fontWeight: '800',
                border: '4px solid #ffffff',
                boxShadow: '0 4px 12px rgba(15,23,42,0.15)',
                marginTop: '-42px',
                marginBottom: '12px',
            },
            '.tmpl-profile-name': {
                fontSize: '1.25rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0',
            },
            '.tmpl-profile-role': {
                fontSize: '0.85rem',
                color: '#64748b',
                margin: '4px 0 12px',
            },
            '.tmpl-profile-bio': {
                fontSize: '0.85rem',
                color: '#475569',
                textAlign: 'center',
                lineHeight: '1.6',
                margin: '0 24px 20px',
            },
            '.tmpl-profile-stats': {
                display: 'flex',
                gap: '32px',
                marginBottom: '20px',
            },
            '.tmpl-profile-stat': {
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: '2px',
            },
            '.tmpl-profile-stat-value': {
                fontSize: '1rem',
                fontWeight: '800',
                color: '#0f172a',
            },
            '.tmpl-profile-stat-label': {
                fontSize: '0.7rem',
                color: '#94a3b8',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
            },
            '.tmpl-profile-btn': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 32px',
                borderRadius: '999px',
                fontWeight: '600',
                fontSize: '0.9rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'chat-list',
        title: 'Chat Message List',
        category: 'appshell',
        tags: ['chat', 'messages', 'conversation', 'messaging'],
        html: '<section class="tmpl-chat"><div class="tmpl-chat-header"><h3 class="tmpl-chat-title">Design Team</h3><span class="tmpl-chat-online">● 8 online</span></div><div class="tmpl-chat-thread"><div class="tmpl-chat-msg sent"><p>Morning! Did you get a chance to review the new hero mock?</p><span class="tmpl-chat-time">9:02 AM</span></div><div class="tmpl-chat-msg received"><p>Just did — looks great. Two small notes on spacing.</p><span class="tmpl-chat-time">9:05 AM</span></div><div class="tmpl-chat-msg sent"><p>Noted. Sending updated version in 10 min.</p><span class="tmpl-chat-time">9:07 AM</span></div><div class="tmpl-chat-msg received"><p>Perfect, thanks! 🚀</p><span class="tmpl-chat-time">9:08 AM</span></div></div><div class="tmpl-chat-input"><input type="text" placeholder="Type a message..." /><button>Send</button></div></section>',
        cssData: {
            '.tmpl-chat': {
                maxWidth: '480px',
                margin: '0 auto',
                background: '#ffffff',
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                fontFamily: 'system-ui, sans-serif',
                display: 'flex',
                flexDirection: 'column',
                height: '420px',
            },
            '.tmpl-chat-header': {
                padding: '16px 20px',
                borderBottom: '1px solid #e2e8f0',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
            },
            '.tmpl-chat-title': {
                fontSize: '1rem',
                fontWeight: '700',
                color: '#0f172a',
                margin: '0',
            },
            '.tmpl-chat-online': {
                fontSize: '0.75rem',
                color: '#16a34a',
            },
            '.tmpl-chat-thread': {
                flex: '1',
                overflow: 'auto',
                padding: '20px',
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
            },
            '.tmpl-chat-msg': {
                maxWidth: '75%',
                padding: '10px 14px',
                borderRadius: '12px',
                fontSize: '0.85rem',
                lineHeight: '1.5',
                position: 'relative',
            },
            '.tmpl-chat-msg p': {
                margin: '0 0 4px',
            },
            '.tmpl-chat-msg.sent': {
                alignSelf: 'flex-end',
                background: '#2563eb',
                color: '#ffffff',
                borderBottomRightRadius: '4px',
            },
            '.tmpl-chat-msg.received': {
                alignSelf: 'flex-start',
                background: '#f1f5f9',
                color: '#0f172a',
                borderBottomLeftRadius: '4px',
            },
            '.tmpl-chat-time': {
                fontSize: '0.65rem',
                opacity: '0.7',
            },
            '.tmpl-chat-input': {
                display: 'flex',
                gap: '8px',
                padding: '12px 16px',
                borderTop: '1px solid #e2e8f0',
            },
            '.tmpl-chat-input input': {
                flex: '1',
                padding: '10px 14px',
                border: '1px solid #cbd5e1',
                borderRadius: '999px',
                fontSize: '0.85rem',
                outline: 'none',
            },
            '.tmpl-chat-input button': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 18px',
                borderRadius: '999px',
                fontWeight: '600',
                fontSize: '0.85rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'todo-list',
        title: 'Todo List',
        category: 'appshell',
        tags: ['todo', 'tasks', 'list', 'productivity'],
        html: '<section class="tmpl-todo"><h3 class="tmpl-todo-title">Today\'s tasks</h3><ul class="tmpl-todo-list"><li class="tmpl-todo-item"><input type="checkbox" checked /><span>Review hero mockup with design team</span></li><li class="tmpl-todo-item"><input type="checkbox" checked /><span>Update pricing page copy</span></li><li class="tmpl-todo-item"><input type="checkbox" /><span>Write changelog for v2.1</span></li><li class="tmpl-todo-item"><input type="checkbox" /><span>Prepare onboarding email</span></li><li class="tmpl-todo-item"><input type="checkbox" /><span>Ship the new template pack</span></li></ul><div class="tmpl-todo-footer"><span>2 of 5 done</span><button class="tmpl-todo-btn">+ Add task</button></div></section>',
        cssData: {
            '.tmpl-todo': {
                maxWidth: '440px',
                margin: '0 auto',
                background: '#ffffff',
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                boxShadow: '0 4px 16px rgba(15,23,42,0.06)',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-todo-title': {
                fontSize: '1.15rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0 0 16px',
            },
            '.tmpl-todo-list': {
                listStyle: 'none',
                padding: '0',
                margin: '0 0 16px',
                display: 'flex',
                flexDirection: 'column',
                gap: '4px',
            },
            '.tmpl-todo-item': {
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                padding: '10px 12px',
                borderRadius: '8px',
                fontSize: '0.9rem',
                color: '#334155',
            },
            '.tmpl-todo-item:hover': {
                background: '#f8fafc',
            },
            '.tmpl-todo-item input': {
                width: '16px',
                height: '16px',
                accentColor: '#2563eb',
            },
            '.tmpl-todo-item span': {
                textDecoration: 'line-through',
                color: '#94a3b8',
            },
            '.tmpl-todo-footer': {
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                borderTop: '1px solid #e2e8f0',
                paddingTop: '16px',
                fontSize: '0.8rem',
                color: '#64748b',
            },
            '.tmpl-todo-btn': {
                background: 'transparent',
                color: '#2563eb',
                border: '1px dashed #93c5fd',
                padding: '8px 16px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.8rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'signup-form',
        title: 'Signup Form',
        category: 'forms',
        tags: ['signup', 'register', 'form', 'account'],
        html: '<section class="tmpl-signup"><div class="tmpl-signup-card"><h2 class="tmpl-signup-title">Create your account</h2><p class="tmpl-signup-subtitle">Free forever. No credit card required.</p><form class="tmpl-signup-form"><div class="tmpl-signup-row"><div class="tmpl-signup-field"><label class="tmpl-signup-label" for="su-first">First name</label><input class="tmpl-signup-input" id="su-first" type="text" placeholder="Ada" /></div><div class="tmpl-signup-field"><label class="tmpl-signup-label" for="su-last">Last name</label><input class="tmpl-signup-input" id="su-last" type="text" placeholder="Lovelace" /></div></div><div class="tmpl-signup-field"><label class="tmpl-signup-label" for="su-email">Work email</label><input class="tmpl-signup-input" id="su-email" type="email" placeholder="you@company.com" /></div><div class="tmpl-signup-field"><label class="tmpl-signup-label" for="su-pass">Password</label><input class="tmpl-signup-input" id="su-pass" type="password" placeholder="At least 8 characters" /></div><button class="tmpl-signup-submit" type="submit">Create Account</button></form><p class="tmpl-signup-terms">By signing up you agree to our <a href="#">Terms</a>.</p></div></section>',
        cssData: {
            '.tmpl-signup': {
                minHeight: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'linear-gradient(135deg, #f1f5f9, #e2e8f0)',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-signup-card': {
                background: '#ffffff',
                borderRadius: '16px',
                padding: '40px',
                width: '100%',
                maxWidth: '460px',
                boxShadow: '0 8px 32px rgba(15,23,42,0.08)',
            },
            '.tmpl-signup-title': {
                fontSize: '1.5rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0 0 8px',
            },
            '.tmpl-signup-subtitle': {
                fontSize: '0.9rem',
                color: '#64748b',
                margin: '0 0 28px',
            },
            '.tmpl-signup-form': {
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
            },
            '.tmpl-signup-row': {
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: '12px',
            },
            '.tmpl-signup-field': {
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
            },
            '.tmpl-signup-label': {
                fontSize: '0.85rem',
                fontWeight: '600',
                color: '#334155',
            },
            '.tmpl-signup-input': {
                padding: '10px 14px',
                border: '1px solid #cbd5e1',
                borderRadius: '8px',
                fontSize: '0.9rem',
                outline: 'none',
            },
            '.tmpl-signup-input:focus': {
                borderColor: '#2563eb',
                boxShadow: '0 0 0 3px rgba(37,99,235,0.1)',
            },
            '.tmpl-signup-submit': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '8px',
                fontWeight: '700',
                fontSize: '0.9rem',
                cursor: 'pointer',
                marginTop: '4px',
            },
            '.tmpl-signup-terms': {
                fontSize: '0.8rem',
                color: '#94a3b8',
                textAlign: 'center',
                margin: '20px 0 0',
            },
            '.tmpl-signup-terms a': {
                color: '#2563eb',
                textDecoration: 'none',
            },
        },
        tokens: {
            '--color-primary': '#2563eb',
            '--color-bg': '#f1f5f9',
            '--color-card': '#ffffff',
            '--color-text': '#0f172a',
            '--color-text-muted': '#64748b',
            '--color-border': '#cbd5e1',
            '--radius': '8px',
            '--space': '16px',
            '--font-base': 'system-ui, sans-serif',
        },
    },
    {
        id: 'contact-form',
        title: 'Contact Form',
        category: 'forms',
        tags: ['contact', 'form', 'support', 'message'],
        html: '<section class="tmpl-contact"><div class="tmpl-contact-card"><h2 class="tmpl-contact-title">Get in touch</h2><p class="tmpl-contact-subtitle">We usually reply within one business day.</p><form class="tmpl-contact-form"><div class="tmpl-contact-field"><label class="tmpl-contact-label" for="ct-name">Name</label><input class="tmpl-contact-input" id="ct-name" type="text" placeholder="Your name" /></div><div class="tmpl-contact-field"><label class="tmpl-contact-label" for="ct-email">Email</label><input class="tmpl-contact-input" id="ct-email" type="email" placeholder="you@example.com" /></div><div class="tmpl-contact-field"><label class="tmpl-contact-label" for="ct-msg">Message</label><textarea class="tmpl-contact-input" id="ct-msg" rows="4" placeholder="How can we help?"></textarea></div><button class="tmpl-contact-submit" type="submit">Send Message</button></form></div></section>',
        cssData: {
            '.tmpl-contact': {
                minHeight: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: '#f8fafc',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-contact-card': {
                background: '#ffffff',
                borderRadius: '16px',
                padding: '40px',
                width: '100%',
                maxWidth: '480px',
                boxShadow: '0 8px 32px rgba(15,23,42,0.08)',
            },
            '.tmpl-contact-title': {
                fontSize: '1.5rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0 0 8px',
            },
            '.tmpl-contact-subtitle': {
                fontSize: '0.9rem',
                color: '#64748b',
                margin: '0 0 28px',
            },
            '.tmpl-contact-form': {
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
            },
            '.tmpl-contact-field': {
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
            },
            '.tmpl-contact-label': {
                fontSize: '0.85rem',
                fontWeight: '600',
                color: '#334155',
            },
            '.tmpl-contact-input': {
                padding: '10px 14px',
                border: '1px solid #cbd5e1',
                borderRadius: '8px',
                fontSize: '0.9rem',
                outline: 'none',
                fontFamily: 'inherit',
                resize: 'vertical',
            },
            '.tmpl-contact-input:focus': {
                borderColor: '#2563eb',
                boxShadow: '0 0 0 3px rgba(37,99,235,0.1)',
            },
            '.tmpl-contact-submit': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '12px 24px',
                borderRadius: '8px',
                fontWeight: '700',
                fontSize: '0.9rem',
                cursor: 'pointer',
            },
        },
    },
    {
        id: 'newsletter-form',
        title: 'Newsletter Signup',
        category: 'forms',
        tags: ['newsletter', 'email', 'subscribe', 'form'],
        html: '<section class="tmpl-news"><div class="tmpl-news-inner"><h2 class="tmpl-news-title">Stay in the loop</h2><p class="tmpl-news-subtitle">One email a week with product updates and design tips. No spam, unsubscribe anytime.</p><form class="tmpl-news-form"><input class="tmpl-news-input" type="email" placeholder="Enter your email" /><button class="tmpl-news-btn" type="submit">Subscribe</button></form><p class="tmpl-news-note">Join 12,000+ subscribers</p></div></section>',
        cssData: {
            '.tmpl-news': {
                background: '#0f172a',
                padding: '80px 24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-news-inner': {
                maxWidth: '560px',
                margin: '0 auto',
                textAlign: 'center',
            },
            '.tmpl-news-title': {
                fontSize: '2rem',
                fontWeight: '800',
                color: '#ffffff',
                margin: '0 0 12px',
            },
            '.tmpl-news-subtitle': {
                fontSize: '0.95rem',
                color: '#94a3b8',
                lineHeight: '1.6',
                margin: '0 0 32px',
            },
            '.tmpl-news-form': {
                display: 'flex',
                gap: '8px',
                background: '#ffffff',
                borderRadius: '999px',
                padding: '6px',
                maxWidth: '440px',
                margin: '0 auto 16px',
            },
            '.tmpl-news-input': {
                flex: '1',
                border: 'none',
                padding: '10px 16px',
                borderRadius: '999px',
                fontSize: '0.9rem',
                outline: 'none',
                background: 'transparent',
            },
            '.tmpl-news-btn': {
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '10px 24px',
                borderRadius: '999px',
                fontWeight: '700',
                fontSize: '0.85rem',
                cursor: 'pointer',
                whiteSpace: 'nowrap',
            },
            '.tmpl-news-note': {
                fontSize: '0.75rem',
                color: '#64748b',
                margin: '0',
            },
        },
    },
    {
        id: 'product-grid',
        title: 'Product Grid',
        category: 'ecommerce',
        tags: ['products', 'shop', 'grid', 'store', 'cards'],
        html: '<section class="tmpl-shop"><h2 class="tmpl-shop-title">Featured products</h2><div class="tmpl-shop-grid"><div class="tmpl-product-card"><div class="tmpl-product-thumb"></div><div class="tmpl-product-body"><span class="tmpl-product-cat">Office</span><h3 class="tmpl-product-name">Ergonomic Desk Lamp</h3><span class="tmpl-product-price">$89</span><button class="tmpl-product-btn">Add to cart</button></div></div><div class="tmpl-product-card"><div class="tmpl-product-thumb"></div><div class="tmpl-product-body"><span class="tmpl-product-cat">Travel</span><h3 class="tmpl-product-name">Weekender Duffel</h3><span class="tmpl-product-price">$129</span><button class="tmpl-product-btn">Add to cart</button></div></div><div class="tmpl-product-card"><div class="tmpl-product-thumb"></div><div class="tmpl-product-body"><span class="tmpl-product-cat">Audio</span><h3 class="tmpl-product-name">Noise-Cancelling Headphones</h3><span class="tmpl-product-price">$249</span><button class="tmpl-product-btn">Add to cart</button></div></div><div class="tmpl-product-card"><div class="tmpl-product-thumb"></div><div class="tmpl-product-body"><span class="tmpl-product-cat">Fitness</span><h3 class="tmpl-product-name">Smart Water Bottle</h3><span class="tmpl-product-price">$39</span><button class="tmpl-product-btn">Add to cart</button></div></div></div></section>',
        cssData: {
            '.tmpl-shop': {
                padding: '80px 24px',
                background: '#f8fafc',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-shop-title': {
                fontSize: '2.25rem',
                fontWeight: '800',
                textAlign: 'center',
                color: '#0f172a',
                margin: '0 0 48px',
            },
            '.tmpl-shop-grid': {
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
                gap: '24px',
                maxWidth: '1100px',
                margin: '0 auto',
            },
            '.tmpl-product-card': {
                background: '#ffffff',
                borderRadius: '12px',
                overflow: 'hidden',
                boxShadow: '0 4px 16px rgba(15,23,42,0.06)',
                display: 'flex',
                flexDirection: 'column',
            },
            '.tmpl-product-thumb': {
                height: '160px',
                background: 'linear-gradient(135deg, #e2e8f0, #cbd5e1)',
            },
            '.tmpl-product-body': {
                padding: '20px',
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
                flex: '1',
            },
            '.tmpl-product-cat': {
                fontSize: '0.7rem',
                fontWeight: '700',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
                color: '#64748b',
            },
            '.tmpl-product-name': {
                fontSize: '1rem',
                fontWeight: '700',
                color: '#0f172a',
                margin: '0',
            },
            '.tmpl-product-price': {
                fontSize: '1.1rem',
                fontWeight: '800',
                color: '#2563eb',
            },
            '.tmpl-product-btn': {
                marginTop: '8px',
                background: '#0f172a',
                color: '#ffffff',
                border: 'none',
                padding: '10px 16px',
                borderRadius: '8px',
                fontWeight: '600',
                fontSize: '0.85rem',
                cursor: 'pointer',
            },
            '.tmpl-product-btn:hover': {
                background: '#2563eb',
            },
        },
    },
    {
        id: 'cart-summary',
        title: 'Cart Summary',
        category: 'ecommerce',
        tags: ['cart', 'checkout', 'order', 'shopping'],
        html: '<section class="tmpl-cart"><div class="tmpl-cart-card"><h2 class="tmpl-cart-title">Order summary</h2><div class="tmpl-cart-items"><div class="tmpl-cart-item"><span class="tmpl-cart-item-name">Ergonomic Desk Lamp</span><span class="tmpl-cart-item-price">$89.00</span></div><div class="tmpl-cart-item"><span class="tmpl-cart-item-name">Weekender Duffel</span><span class="tmpl-cart-item-price">$129.00</span></div><div class="tmpl-cart-item"><span class="tmpl-cart-item-name">Smart Water Bottle</span><span class="tmpl-cart-item-price">$39.00</span></div></div><div class="tmpl-cart-lines"><div class="tmpl-cart-line"><span>Subtotal</span><span>$257.00</span></div><div class="tmpl-cart-line"><span>Shipping</span><span>Free</span></div><div class="tmpl-cart-line total"><span>Total</span><span>$257.00</span></div></div><button class="tmpl-cart-btn">Proceed to Checkout</button><p class="tmpl-cart-note">Taxes calculated at checkout.</p></div></section>',
        cssData: {
            '.tmpl-cart': {
                minHeight: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: '#f1f5f9',
                padding: '24px',
                fontFamily: 'system-ui, sans-serif',
            },
            '.tmpl-cart-card': {
                background: '#ffffff',
                borderRadius: '16px',
                padding: '32px',
                width: '100%',
                maxWidth: '420px',
                boxShadow: '0 8px 32px rgba(15,23,42,0.08)',
            },
            '.tmpl-cart-title': {
                fontSize: '1.25rem',
                fontWeight: '800',
                color: '#0f172a',
                margin: '0 0 24px',
            },
            '.tmpl-cart-items': {
                display: 'flex',
                flexDirection: 'column',
                gap: '12px',
                paddingBottom: '20px',
                borderBottom: '1px solid #e2e8f0',
                marginBottom: '20px',
            },
            '.tmpl-cart-item': {
                display: 'flex',
                justifyContent: 'space-between',
                fontSize: '0.9rem',
            },
            '.tmpl-cart-item-name': {
                color: '#334155',
            },
            '.tmpl-cart-item-price': {
                color: '#0f172a',
                fontWeight: '600',
            },
            '.tmpl-cart-lines': {
                display: 'flex',
                flexDirection: 'column',
                gap: '10px',
                marginBottom: '24px',
            },
            '.tmpl-cart-line': {
                display: 'flex',
                justifyContent: 'space-between',
                fontSize: '0.9rem',
                color: '#64748b',
            },
            '.tmpl-cart-line.total': {
                fontSize: '1.05rem',
                fontWeight: '800',
                color: '#0f172a',
                borderTop: '1px solid #e2e8f0',
                paddingTop: '12px',
            },
            '.tmpl-cart-btn': {
                width: '100%',
                background: '#2563eb',
                color: '#ffffff',
                border: 'none',
                padding: '14px 24px',
                borderRadius: '10px',
                fontWeight: '700',
                fontSize: '0.95rem',
                cursor: 'pointer',
            },
            '.tmpl-cart-note': {
                fontSize: '0.75rem',
                color: '#94a3b8',
                textAlign: 'center',
                margin: '12px 0 0',
            },
        },
    },
];
